# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be906015eadb5ce8eeac530c87c828215300bfc8df6a37b78f90988c7875cc27b718cb34b5c74587e8d827ff68ddbca9d45215d58f49c9c86c59b0045e17f24b

test:
  secret_key_base: 8a463fcb46881054cd85cb48c448d33dad5846a466c9834ed5908ae7f0a467187e4c85285b557399fb596464aa1aa04393e3fae811c5f857b1a538a14c42933b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
